config/routes.rb
  PoliTodo::Application.routes.draw do

  devise_for :users
  resources :projects
  resources :tasks

  match "/tasks/:id/mark_as_done" => "tasks#mark_as_done"
  match "/tasks/:id/restart_task" => "tasks#restart_task"

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :subject
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :projects
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name,:email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  def new
  end

  def create
        project = Project.new()
	    project.name = params[:name]
       	project.where = params[:where]
        project.project_type = 1 
        project.subject_id = params[:subject_id]
        project.deadline= DateTime.parse(params[:when])
        project.priority = params[:priority]
        project.other_details = params[:other_details]
        project.save
        redirect_to "/projects"
  end

	def index
      @projects = Project.all
	end

	def show
    @project = Project.where(:id => params[:id]).first

    @completed_tasks = Task.where(:project_id => params[:id], :status => 1)
    @uncompleted_tasks = Task.where(:project_id => params[:id], :status => [0, nil])
    
    @hash_t = [] 
    @hash_t[1] = "low"
    @hash_t[2] = "medium"
    @hash_t[3] = "high"
    @hash_t[4] = "Your life depends on it!" 
  end
    

  def edit
    @project = Project.where(:id => params[:id]).first()
  end
  
  def update
        project = Project.where(:id => params[:id]).first()
	    project.name = params[:name]
       	project.where = params[:where]
        project.project_type = 1 
        project.subject_id = params[:subject_id]
        project.deadline= DateTime.parse(params[:when])
        project.priority = params[:priority]
        project.other_details = params[:other_details]
        project.save
        redirect_to "/projects"
  end

  def destroy
   Project.delete_all(:id => params[:id])
   redirect_to "/projects"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    task = Task.new()
    task.project_id = params[:project_id] 
    task.user_id = params[:user_id]
    task.description = params[:description]
    task.save
    redirect_to "/projects/#{task.project_id}"
  end

  def mark_as_done
    task = Task.find(params[:id])
    task.update_attributes(:status => 1)
    redirect_to "/projects/#{task.project_id}"
  end

  def restart_task
    task = Task.find(params[:id])
    task.update_attributes(:status => nil)
    redirect_to "/projects/#{task.project_id}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tets_helper.rb
module TetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoliTodo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body style = "background: url(/assets/background.jpg) no-repeat; background-size: 100%;">

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a href="#" class="brand">Notify me</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Homework</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Tests and exams</a></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">School facts<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Introduction to operating systems</a></li>
                <li><a href="#">Logic Design<</a></li>
                <li><a href="#">Data structures</a></li>
								<li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Object Oriented Programming</a></li>
                <li><a href="#">Algorithm Design</a></li>
                <li><a href="#">Programming paradigms</a></li>
              </ul>
            </li>
          </ul>
          <form action="" class="navbar-search pull-left">
            <input type="text" placeholder="Search" class="search-query span2">
          </form>
          
				<ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">Sort by<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Date</a></li>
                <li><a href="#">School facts</a></li>
                <li><a href="#">Priority</a></li>
              </ul>
            </li>
          </ul>


        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div>

<div class = "row">
<div class = "span8 offset2">

<div class="hero-unit">
  <%= form_tag ({:controller => "projects", :action => "update"}), ({:method => "PUT"}) do %>
        <h2>Edit homework task</h2>
				<br>
				<br>
				<table>
				<tr>
				<td >
				<span class="label label-important" >Name</span> 
				</td>			
				<td style = "padding-left: 30px;">				
				<input type="text" name="name" value="<%= @project.name %>" style="height: 30px; padding-left: 30px;" />
				</td>				
				</tr>	
	
				<tr>
				<td>
				<span class="label label-important">Edit Type</span> 
				</td>				
				<td style = "padding-left: 30px;">
				<input type="text" name="type" value="1" style="height: 30px; padding-left: 30px;"/>
				</td>		
				</tr>				
				<tr>
				<td>		
				<span class="label label-important">Edit School fact</span> 
				</td>
				<td style = "padding-left: 30px;">				
				<select name="subject_id" >
                    <% Subject.all.each do |subject| %>
                        <option value =" <%= subject.id %>"> <%= subject.name %> </option>
                    <% end %>
        
				</select>
				</td>				
				</tr>
				<tr>
				<td>
				<span class="label label-important">Edit When</span> 
				</td>
				<td style = "padding-left: 30px;">
				<input type="text" name="when" value="<%= @project.deadline.to_s %>" style="height: 30px; padding-left: 30px;"/>
				</td>	
				</tr>				
				<tr>
				<td>
				<span class="label label-important">Edit Where</span> 
				</td>
				<td style = "padding-left: 30px;">
				<input type="text" name="where" value="<%= @project.where %>" style="height: 30px; padding-left: 30px;"/>			
				</td>
				</tr>				
				<tr>
				<td>
				<span class="label label-important">Edit Priority</span>       
				</td>
				<td style = "padding-left: 30px; value="<%= @project.priority %>">
				<select >
				<option> High </option>
				<option> Medium </option>
				<option> Low </option>
				</select>
				</td>
				</tr>				
					<tr>		
						<td>
							<span class="label label-important" value="<%= @project.priority %>">Edit Other details</span>       
						</td>
						<td style = "padding-left: 30px;">				
							<textarea  rows="40"  name="other" style="height: 30px; padding-left: 30px;"></textarea>				
						</td>	
					</tr>		
				</table>
        <input style="float:right;" class="badge badge-inverse" type="submit" value="Add it!" />
  <% end %>
</div>
</div> 

<div class = "span4">

<div style="padding: 8px 0;" class="well">
        <ul class="nav nav-list">
          <li class="nav-header">I am logged in as</li>
          <li><a href="#"><i class="icon-user"></i> Username</a></li>
          <li class="divider"></li>
          <li><input type="submit" value="Log out."></li>
        </ul>
</div>

<div style="padding: 8px 0;" class="well">
        <ul class="nav nav-list">
          <li class="nav-header">My account</li>
          <li><a href="#"><i class="icon-user"></i> Profile</a></li>
          <li><a href="#"><i class="icon-cog"></i> Settings</a></li>
          <li class="divider"></li>
          <li><a href="#"><i class="icon-flag"></i> Help</a></li>
        </ul>
</div>
</div>

</div>

app/views/projects/index.html.erb
<div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a href="#" class="brand">Notify me</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="/">Homework</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Tests and exams</a></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">School facts<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Introduction to operating systems</a></li>
                <li><a href="#">Logic Design<</a></li>
                <li><a href="#">Data structures</a></li>
								<li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Object Oriented Programming</a></li>
                <li><a href="#">Algorithm Design</a></li>
                <li><a href="#">Programming paradigms</a></li>
              </ul>
            </li>
          </ul>
          <form action="" class="navbar-search pull-left">
            <input type="text" placeholder="Search" class="search-query span2">
          </form>
          
				<ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">Sort by<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Date</a></li>
                <li><a href="#">School facts</a></li>
                <li><a href="#">Priority</a></li
              </ul>
            </li>
          </ul>


        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div>

<div class = "row">
<div class = "span8 offset2">
<div class="hero-unit">
        <h2>My homework tasks</h2>
				<br>
        <ul>
	<table align="center" class="table table-striped">
		<thead>
			<tr>
			<th>Title </th>
			<th>Deadline</th>
			<th>Options</th>
			</tr>
		</thead>
          <% @projects.each do |project| %>
              
              <tr>
                <td style="padding-right:10px"> 
                  <font size="4">
                    <%=project.name %>
                    </font>
                </td>
                <td style="padding-right:10px">
                 <span class="label label"><%= project.deadline.to_s %></span> 
                </td>
                <td style="padding-right:10px">
                 <input class="btn btn-success" type="button" value="Modify" id="modify_index">
                </td>
                <td style="padding-right:10px">
                  <a href="/projects/<%=project.id%>" class="btn btn-primary" type="button" >View </a>
                </td>
                <td style="padding-right:	0px">
                  <%=  link_to('Delete',"/projects/#{project.id}" , :method => :delete, :class => "btn btn-danger") %> 
                </td>

              </tr>
          <% end %>
	</table>          
        </ul>
   
				<ul class="pager">
				<li class="previous">
		    <a href="#">&larr; Older</a>
    		</li>
    		<li class="next">
    		<a href="#">Newer &rarr;</a>
    		</li>
    		</ul>
      </div>

</div class = "span8">
<div class = "span4">
  <div style="padding: 8px 0;" class="well">
          <ul class="nav nav-list">
            <li class="nav-header">I am logged in as</li>
            <li><a href="#"><i class="icon-user"></i><%= !current_user.name.blank? ? current_user.name : current_user.email %></a></li>
            <li class="divider"></li>
            <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "btn span1") %> 
            </li>
          </ul>
  </div>

  <div style="padding: 8px 0;" class="well">
          <ul class="nav nav-list" >
            <li class="nav-header">Another list header</li>
            <li><a href="#"><i class="icon-user"></i> Profile</a></li>
            <li><a href="#"><i class="icon-cog"></i> Settings</a></li>
            <li><a href="/projects/new"><i class="icon-cog"></i> New 
            Homework</a></li>
            <li class="divider"></li>
            <li><a href="#"><i class="icon-flag"></i> Help</a></li>
          </ul>
        </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a href="#" class="brand">Notify me</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Homework</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Tests and exams</a></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">School facts<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Introduction to operating systems</a></li>
                <li><a href="#">Logic Design<</a></li>
                <li><a href="#">Data structures</a></li>
								<li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Object Oriented Programming</a></li>
                <li><a href="#">Algorithm Design</a></li>
                <li><a href="#">Programming paradigms</a></li>
              </ul>
            </li>
          </ul>
          <form action="" class="navbar-search pull-left">
            <input type="text" placeholder="Search" class="search-query span2">
          </form>
          
				<ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">Sort by<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Date</a></li>
                <li><a href="#">School facts</a></li>
                <li><a href="#">Priority</a></li>
              </ul>
            </li>
          </ul>


        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div>

<div class = "row">
<div class = "span8 offset2">

<div class="hero-unit">
  <%= form_tag ({:controller => "projects", :action => "create"}), ({:method => "POST"}) do %>
        <h2>Insert new homework task</h2>
				<br>
				<br>
				<table>
				<tr>
				<td >
				<span class="label label-important" >Name</span> 
				</td>			
				<td style = "padding-left: 30px;">				
				<input type="text" name="name" style="height: 30px; padding-left: 30px;" />
				</td>				
				</tr>	
	
				<tr>
				<td>
				<span class="label label-important">Type</span> 
				</td>				
				<td style = "padding-left: 30px;">
				<input type="text" name="type" style="height: 30px; padding-left: 30px;"/>
				</td>		
				</tr>				
				<tr>
				<td>		
				<span class="label label-important">School fact</span> 
				</td>
				<td style = "padding-left: 30px;">				
				<select name="subject_id" >
        <% Subject.all.each do |subject| %>
        <option value =" <%= subject.id %>"> <%= subject.name %> </option>
        <% end %>
        
				</select>
				</td>				
				</tr>
				<tr>
				<td>
				<span class="label label-important">When</span> 
				</td>
				<td style = "padding-left: 30px;">
				<input type="text" name="when" style="height: 30px; padding-left: 30px;"/>
				</td>	
				</tr>				
				<tr>
				<td>
				<span class="label label-important">Where</span> 
				</td>
				<td style = "padding-left: 30px;">
				<input type="text" name="where" style="height: 30px; padding-left: 30px;"/>			
				</td>
				</tr>				
				<tr>
				<td>
				<span class="label label-important">Priority</span>       
				</td>
				<td style = "padding-left: 30px;">
				  <select name="priority">
				    <option value="1"> Low </option>
				    <option value="2">  Medium </option>
	          <option value="3"> High </option>
            <option value="4"> Your life depends on it  </option>
				  </select>
				</td>
				</tr>				
					<tr>		
						<td>
							<span class="label label-important">Other details</span>       
						</td>
						<td style = "padding-left: 30px;">				
							<textarea  rows="40"  name="other_details" style="height: 30px; padding-left: 30px;"></textarea>				
						</td>	
					</tr>		
				</table>
        <input style="float:right;" class="badge badge-inverse" type="submit" value="Add it!" />
  <% end %>
</div>
</div> 

<div class = "span4">

<div style="padding: 8px 0;" class="well">
        <ul class="nav nav-list">
          <li class="nav-header">I am logged in as</li>
          <li><a href="#"><i class="icon-user"></i> Username</a></li>
          <li class="divider"></li>
          <li><input type="submit" value="Log out."></li>
        </ul>
</div>

<div style="padding: 8px 0;" class="well">
        <ul class="nav nav-list">
          <li class="nav-header">My account</li>
          <li><a href="#"><i class="icon-user"></i> Profile</a></li>
          <li><a href="#"><i class="icon-cog"></i> Settings</a></li>
          <li class="divider"></li>
          <li><a href="#"><i class="icon-flag"></i> Help</a></li>
        </ul>
</div>
</div>

</div>

app/views/projects/show.html.erb
  <link rel="stylesheet" type="text/css" href="assets/unique_ss/details_style.css"/>
<div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a href="#" class="brand">Notify me</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Homework</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Tests and exams</a></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">School facts<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Introduction to operating systems</a></li>
                <li><a href="#">Logic Design<</a></li>
                <li><a href="#">Data structures</a></li>
								<li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Object Oriented Programming</a></li>
                <li><a href="#">Algorithm Design</a></li>
                <li><a href="#">Programming paradigms</a></li>
              </ul>
            </li>
          </ul>
          <form action="" class="navbar-search pull-left">
            <input type="text" placeholder="Search" class="search-query span2">
          </form>
          
				<ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">Sort by<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Date</a></li>
                <li><a href="#">School facts</a></li>
                <li><a href="#">Priority</a></li>
              </ul>
            </li>
          </ul>


        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div>
    
<div class="span8 offset2">
<div class="hero-unit">
	<div class="container">
            
            <ul>
                <li>
                   <p>Titlu: <%= @project.name %> </p>
                </li>
                <li>
                  <p>Materia : <%= @project.subject.name %> </p>
                </li>
                <li>
                  <p>Prioriate : <%= @hash_t[@project.priority]%><p>
                </li>
                <li>
                    <p>Deadline : <script language="JavaScript">
                    
                    TargetDate =<%=@project.deadline.strftime('%M/%D/%Y %H:%M %p')%>;
                    BackColor = "lightblue";
                    ForeColor = "navy";
                    CountActive = true;
                    CountStepper = -1;
                    LeadingZero = true;
                    DisplayFormat = "%%D%% Zile, %%H%% Ore, %%M%% Minute, %%S%% Secunde.";
                    FinishMessage = "Tema trebuia predata!!!";
                                  </script>
                    </p>
                   <script language="JavaScript" src="http://scripts.hashemian.com/js/countdown.js"></script>
                </li>
                <li>
                  <p>Enunt: <%= @project.other_details %>
                </li>
            </ul>
    </div>

    <div id="tasks">
      <% if @uncompleted_tasks.size > 0 %>
        <p>Uncompleted Tasks</p>
          <% @uncompleted_tasks.each do |task| %>
            <div class="row">
              <div class="span5">
                <%=task.description %>
              </div>
              <div class="span1">
                <%= link_to "Done it!", "/tasks/#{task.id}/mark_as_done" %>
              </div>
            </div>
          <% end %>
      <% end %>

      <% if @completed_tasks.size > 0 %>
        <p>Completed Tasks</p>
          <% @completed_tasks.each do |task| %>
            <div class="row">
              <div class="span5">
                <strike><%= task.description %></strike>
              </div>
              <div class="span1">
                <%= link_to "Restart", "/tasks/#{task.id}/restart_task" %>
              </div>
            </div>
          <%end %>
      <% end %>
    </div>

    <%= form_tag ({:controller => "tasks", :action => "create"}), ({:method =>  :post}) do %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= hidden_field_tag :project_id, @project.id %>
      <%= text_field_tag :description %>
      <%= submit_tag "Add task"%>
    <% end %>
</div>
</div>
<div class = "span4">

<div style="padding: 8px 0;" class="well">
        <ul class="nav nav-list">
          <li class="nav-header">I am logged in as</li>
          <li><a href="#"><i class="icon-user"></i> Username</a></li>
          <li class="divider"></li>
          <li><input type="submit" value="Log out."></li>
        </ul>
</div>

<div style="padding: 8px 0;" class="well">
        <ul class="nav nav-list">
          <li class="nav-header">My account</li>
          <li><a href="#"><i class="icon-user"></i> Profile</a></li>
          <li><a href="#"><i class="icon-cog"></i> Settings</a></li>
          <li class="divider"></li>
          <li><a href="#"><i class="icon-flag"></i> Help</a></li>
        </ul>
</div>
</div>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>